# docker-compose.yml
version: "3.4"

services:
  flask-server:
    image: flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data-proskell:/var/data

volumes:
  data-proskell:
    external: true
